### PR TITLE
Fix AppVeyor deploy, take four

### PR DESCRIPTION
**Pull request by madig**
This reverts commit 7456fb843a32a12ae6cfbf5c1cc8a5ab055d9dee. Try the PowerShell hack.

### CODE REVIEW

**Comment by anthrotype** [comment]
what was wrong with the previous one?

**Comment by madig** [comment]
https://ci.appveyor.com/project/rougier/freetype-py/build/1.0.99/job/8cc0lskcbi7i43fn#L1128

😢

**Comment by anthrotype** [comment]
it doesn't make sense.. it does find it inside `dist` for the artifacts upload:
https://ci.appveyor.com/project/rougier/freetype-py/build/1.0.99/job/8cc0lskcbi7i43fn#L1103

jeez, Windows.. try a backslash?

**Comment by anthrotype** [comment]
and this works every time with afdko repository

https://github.com/adobe-type-tools/afdko/blob/develop/.appveyor.yml#L37

**Comment by madig** [comment]
> ls : Cannot find path 'C:\projects\freetype-py\tests\dist' because it does not exist.

hm?!

**Comment by anthrotype** [comment]
wtf

**Comment by anthrotype** [comment]
it changed directory!

**Comment by anthrotype** [comment]
it should be one level up...

**Comment by madig** [comment]
Ah, we `cd tests` further up... let's see.

**Comment by anthrotype** [comment]
why?!

**Comment by anthrotype** [comment]
ah we do that to make sure we run the tests against the installed package, not the one in the current working dir...

**Pull request merged**
