### PR TITLE
Correct the license classifier

### PR DESCRIPTION
**Pull request by bgermann**
The project is BSD licensed.

### CODE REVIEW

**Comment by HinTak** [comment]
Hmm, that line came from the initial import, and in the same file at that particular commit, at the top of the file it says BSD, and it is also BSD almost everywhere else (both historically and across the source tree). So I think Nicolas really meant BSD.

BTW, only Nicolas is supposed to declare "the project is X licensed"...

**Comment by rougier** [comment]
Yes, I meant BSD.

**Comment by topazus** [comment]
@rougier @HinTak Hello, What is the SPDX License name of the project?

**Comment by bgermann** [comment]
The license identifier is BSD-3-Clause, even though the documented license text differs in clause 3: "Neither the name of the copyright holder..." vs. "Neither the name of the freetype-py Development Team..."

**Pull request merged**
