### PR TITLE
Drop Python 2 support, revamp CI

### PR DESCRIPTION
**Pull request by madig**
This PR

1. Drops Python 2 support but does not clean up the code.
2. Switches from Travis and Appveyor to GitHub Actions for simplicity.
3. Drops 32 bit wheels and ups the macOS deployment target to 10.9.

I also modified the setup requirements to include cmake (so stuff just builds without requiring a separate CMake installation) and certifi (the macOS CI runner seems to not have certificate authorities installed, leading to download failures).

### CODE REVIEW

**Comment by madig** [comment]
@rougier Did someone unhook Travis?

**Comment by rougier** [comment]
I did not. I just checked the Travis settings and everything looks ok but there are now a bunch of options on when to activate it (don't remember these settings). Do you have access to these settings ?

**Comment by madig** [comment]
This repo doesn't show up in my Travis dashboard, so I probably don't have access?

**Comment by rougier** [comment]
Mayb we shoud migrate to GitHub action. I've checked Travis and last build is 6 months old. So something went wrong at some point but I can't locate the problem right now.

**Comment by madig** [comment]
Sounds good, once I figure out how to make wheels for all platforms on GHA.

**Pull request merged**
