### PR TITLE
Update bundler script to use FreeType 2.9.1

### PR DESCRIPTION
**Pull request by madig**
I think it is time for a version bump and a release :)

### CODE REVIEW

**Comment by madig** [comment]
Dayum.

**Comment by madig** [comment]
Oh no! I forgot to create ftconfig.h on Windows :confounded:

**Comment by madig** [comment]
Upstream in freetype git, yes. Now I either have to patch the cmake file
here or hope for a new release. Maybe I'll just overwrite the cmake file...

**Comment by madig** [comment]
Oh FFS. The Windows build seems to not generate a shared library...

**Comment by madig** [comment]
You can merge now.

**Comment by rougier** [comment]
Thanks !

**Pull request merged**
