### PR TITLE
Split the ctypes function binding out into raw.py.

### PR DESCRIPTION
**Pull request by mdsitton**
This should make things a bit better for people who want to use the ctypes binding directly, instead of the pythonic wrapper.

This still may need some work, and i haven't tested it thoroughly.

### CODE REVIEW

**Comment by rougier** [comment]
Good idea but it could be better to have the raw stuff in the__init__ and the pythonic api in another file, no ?

**Comment by mdsitton** [comment]
Possibly, but my reasoning is as follows:
1. Keep compatibility with all current code
2. Allow one to use only the raw api and not have to pull in the pythonic api.

**Comment by rougier** [comment]
Make sense. I'll test it and I'll merge (if tests are ok of course)

**Comment by mdsitton** [comment]
I do think it might be a good idea to logically split up, and move stuff out of __init__.py for maintainability reasons.

**Comment by mdsitton** [comment]
Any updates on merging?

**Comment by rougier** [comment]
Sorry, I forgot... Just merge it. Thanks.

**Comment by mdsitton** [comment]
No problem.

**Pull request merged**
