### PR TITLE
add support for building zlib and libpng libraries in setup-build-freetype.py

### PR DESCRIPTION
**Pull request by mammo0**
Hello,

this PR is for solving #123.

Building with zlib or libpng support is disabled by default. So there's no new default behavior of this script.
But if you want to build with

- zlib support, set the environment variable `FREETYPEPY_WITH_ZLIB` to some value, e.g. `1`
- libpng support, set the environment variable `FREETYPEPY_WITH_LIBPNG` to some value, e.g. `1`

### CODE REVIEW

**Comment by HinTak** [comment]
If you bundle very common libraries like zlib and libpng you might need to look into the symbol export systems (not sure about it under cmake etc, but it is part of autoconf'ed build) not to re-export 3rd-party symbols, to avoid the Linux version of dll hell - where software using freetype **and*/ libpng get confused by the bundled libpng symbols within your build of freetype.

**Comment by mammo0** [comment]
Well, honestly I've got not the knowledge of how the re-export of the symbols can be prevented.

I have oriented myself on how `harfbuzz` was built into the freetype library. After it worked for me, I just opened the PR here...

**Comment by HinTak** [comment]
The autoconf build of freetype sets symbols to be by default hidden, and passes a linker script to the linker to explicitly declare which symbols are exported.

**Comment by mammo0** [comment]
Ok, can you show me an example?

**Comment by HinTak** [comment]
You can each for export in freetype e.g. https://git.savannah.gnu.org/cgit/freetype/freetype2.git/commit/?id=771d3c8ae25d5042a3f6b76a329ad3dd782eca66

**Comment by mammo0** [comment]
So the variable `EXPORTS_LIST` should be set?

I'm sorry, but I don't have much experience in C/C++ and library programming... So maybe you can make the necessary changes? Because it seems you know what you're talking about...

**Pull request closed without merging**
